// Auto-generated by Agent/scripts/export-registry.mjs — do not edit
// Generated: 2026-03-09T02:08:57.124Z
// Lessons with data: 41
const LESSON_REGISTRY = {
  "6.10": {
    "unit": 6,
    "lesson": 10,
    "urls": {
      "worksheet": "https://robjohncolson.github.io/apstats-live-worksheet/u6_lesson10_live.html",
      "drills": "https://lrsl-driller.vercel.app/platform/app.html?c=apstats-u6-inference-prop&level=l17-hypotheses-610",
      "quiz": "https://robjohncolson.github.io/curriculum_render/?u=6&l=9",
      "blooket": "https://dashboard.blooket.com/set/69ad1cce0d5874349dbbf688",
      "schoologyFolder": null,
      "videos": [
        "1dIRMyHdePpkx7pCJFcAkRHIPj2Q8RtqG",
        "1SDYELDZa9kcJldq_qf1DsOOMhrjzfkio"
      ]
    },
    "status": {
      "ingest": "done",
      "worksheet": "done",
      "drills": "done",
      "blooketCsv": "done",
      "blooketUpload": "done",
      "animations": "skipped",
      "schoology": "done"
    }
  },
  "6.11": {
    "unit": 6,
    "lesson": 11,
    "urls": {
      "worksheet": "https://robjohncolson.github.io/apstats-live-worksheet/u6_lesson11_live.html",
      "drills": "https://lrsl-driller.vercel.app/platform/app.html?c=apstats-u6-inference-prop&level=l21-zstat-611",
      "quiz": "https://robjohncolson.github.io/curriculum_render/?u=6&l=10",
      "blooket": "https://dashboard.blooket.com/set/69ade09c572efa156e0e3402",
      "schoologyFolder": null,
      "videos": []
    },
    "status": {
      "ingest": "done",
      "worksheet": "done",
      "drills": "done",
      "blooketCsv": "done",
      "blooketUpload": "done",
      "animations": "done",
      "schoology": "done"
    }
  },
  "6.7": {
    "unit": 6,
    "lesson": 7,
    "urls": {
      "worksheet": "https://robjohncolson.github.io/apstats-live-worksheet/u6_lesson7_live.html",
      "drills": "https://lrsl-driller.vercel.app/platform/app.html?c=apstats-u6-inference-prop&level=l35-identify-error-type",
      "quiz": "https://robjohncolson.github.io/curriculum_render/?u=6&l=6",
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=986400679",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "pending"
    }
  },
  "1.3": {
    "unit": 1,
    "lesson": 3,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=947992805",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "1.4": {
    "unit": 1,
    "lesson": 4,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=947992805",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "1.5": {
    "unit": 1,
    "lesson": 5,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=947992805",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "1.6": {
    "unit": 1,
    "lesson": 6,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=947992805",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "1.7": {
    "unit": 1,
    "lesson": 7,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=948168199",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "1.8": {
    "unit": 1,
    "lesson": 8,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=949296571",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "1.9": {
    "unit": 1,
    "lesson": 9,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=949903740",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "1.10": {
    "unit": 1,
    "lesson": 10,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=950173574",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "2.1": {
    "unit": 2,
    "lesson": 1,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=954330871",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "2.2": {
    "unit": 2,
    "lesson": 2,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=954636359",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "2.3": {
    "unit": 2,
    "lesson": 3,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=955309456",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "2.4": {
    "unit": 2,
    "lesson": 4,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=957153701",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "2.5": {
    "unit": 2,
    "lesson": 5,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=959200382",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "2.6": {
    "unit": 2,
    "lesson": 6,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=960099957",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "2.7": {
    "unit": 2,
    "lesson": 7,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=961457155",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "3.4": {
    "unit": 3,
    "lesson": 4,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=970432845",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "3.5": {
    "unit": 3,
    "lesson": 5,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=971289382",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "4.3": {
    "unit": 4,
    "lesson": 3,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=976933461",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "4.6": {
    "unit": 4,
    "lesson": 6,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=978369747",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "4.7": {
    "unit": 4,
    "lesson": 7,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=979189351",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "4.8": {
    "unit": 4,
    "lesson": 8,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=979189351",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "4.9": {
    "unit": 4,
    "lesson": 9,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=979189351",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "5.1": {
    "unit": 5,
    "lesson": 1,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=980335378",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "5.2": {
    "unit": 5,
    "lesson": 2,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=980334396",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "5.3": {
    "unit": 5,
    "lesson": 3,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=981293561",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "5.4": {
    "unit": 5,
    "lesson": 4,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=981564763",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "5.5": {
    "unit": 5,
    "lesson": 5,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=981770601",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "5.6": {
    "unit": 5,
    "lesson": 6,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=982382766",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "5.7": {
    "unit": 5,
    "lesson": 7,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=982382766",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "5.8": {
    "unit": 5,
    "lesson": 8,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=984565607",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "6.1": {
    "unit": 6,
    "lesson": 1,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=985196978",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "6.2": {
    "unit": 6,
    "lesson": 2,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=985597961",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "6.3": {
    "unit": 6,
    "lesson": 3,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=985937488",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "6.4": {
    "unit": 6,
    "lesson": 4,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=986218661",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "6.5": {
    "unit": 6,
    "lesson": 5,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=986218661",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "6.6": {
    "unit": 6,
    "lesson": 6,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=986400679",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "6.8": {
    "unit": 6,
    "lesson": 8,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=986444841",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  },
  "6.9": {
    "unit": 6,
    "lesson": 9,
    "urls": {
      "worksheet": null,
      "drills": null,
      "quiz": null,
      "blooket": null,
      "schoologyFolder": "https://lynnschools.schoology.com/course/7945275782/materials?f=986454317",
      "videos": []
    },
    "status": {
      "ingest": "pending",
      "worksheet": "pending",
      "drills": "pending",
      "blooketCsv": "pending",
      "blooketUpload": "pending",
      "animations": "pending",
      "schoology": "scraped"
    }
  }
};
