// gitnexus-shadow.test.js — the tracked .gitnexus-shadow/*.inline.js files must be
// exactly what scripts/gitnexus-shadow.mjs derives from the current HTML apps
// (line-preserving), or GitNexus impact analysis on the Desk goes stale.
// Regenerate: `npm run gitnexus:shadow` (or `npm run gitnexus:analyze`).
// @vitest-environment node
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { shadowOf, shadowFileName, SHADOWED_APPS } from '../scripts/gitnexus-shadow.mjs';

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..');

describe('shadowOf (pure)', () => {
  it('keeps only inline script lines and preserves line count', () => {
    const html = '<!DOCTYPE html>\n<script src="x.js"></script>\n<script>\nvar a = 1;\n</script>\n<p>hi</p>\n<script>one();</script>\n';
    const out = shadowOf(html).split('\n');
    expect(out.length).toBe(html.split('\n').length);
    expect(out[0]).toBe('');
    expect(out[1]).toBe('');            // external script skipped
    expect(out[3]).toBe('var a = 1;');
    expect(out[5]).toBe('');
    expect(out[6]).toBe('one();');      // one-line inline script
  });
  it('neutralizes HTML-like comments inside scripts so the shadow parses as JS', () => {
    const html = '<script>\n<!-- old-browser guard\nvar x = 1;\n-->\n</script>';
    const out = shadowOf(html).split('\n');
    expect(out[1]).toBe('//<!-- old-browser guard');
    expect(out[3]).toBe('//-->');
  });
});

describe('tracked shadows are fresh', () => {
  for (const rel of SHADOWED_APPS) {
    it(`${rel} → .gitnexus-shadow/${shadowFileName(rel)} matches the current HTML (line-preserving)`, () => {
      const src = resolve(repo, rel);
      if (!existsSync(src)) return;   // app removed: shadow list should be updated, but do not fail unrelated runs
      const shadowPath = resolve(repo, '.gitnexus-shadow', shadowFileName(rel));
      expect(existsSync(shadowPath), `missing shadow — run npm run gitnexus:shadow`).toBe(true);
      const html = readFileSync(src, 'utf8');
      const expected = shadowOf(html).split('\n');
      const actual = readFileSync(shadowPath, 'utf8').split('\n');
      expect(actual.length).toBe(expected.length);
      // Line 1 carries the generated header; every other line must match exactly.
      expect(actual[0]).toMatch(/^\/\/ GENERATED by scripts\/gitnexus-shadow\.mjs/);
      for (let i = 1; i < expected.length; i += 1) {
        if (actual[i] !== expected[i]) {
          throw new Error(`stale shadow for ${rel} at line ${i + 1} — run npm run gitnexus:shadow`);
        }
      }
    });
  }
});
