// GENERATED by scripts/gitnexus-shadow.mjs from start-here.html — line numbers match the HTML. Do not edit.





























































































































































































































































































































































































































































































































































































































































































































































    (function () {
      'use strict';

      // === v3 ENGINE (copied verbatim; displayed numbers MUST equal the server's) ===
      var V3_WORK_WEIGHTS = { lessons: 0.30, quizzes: 0.30, posters: 0.30, blooket: 0.10 };
      function quarterGradeV3(pc, work) { // both on 0..1
        if (pc >= 0.40 && work >= 0.40) return Math.max(pc, work);
        return Math.max(0.7 * pc, 0.7 * work, (pc + work) / 2);
      }
      function workAvgV3(tracks) { // {lessons,quizzes,posters,blooket} each 0..1 or null; renormalizes over present
        var num = 0, den = 0;
        for (var k in V3_WORK_WEIGHTS) {
          var v = tracks[k]; if (v == null) continue;
          num += V3_WORK_WEIGHTS[k] * v; den += V3_WORK_WEIGHTS[k];
        }
        return den === 0 ? null : num / den;
      }
      function combineV3(pc, work) { // tolerates a null track
        if (pc == null && work == null) return null;
        if (pc == null) return work;
        if (work == null) return pc;
        return quarterGradeV3(pc, work);
      }
      // === END v3 ENGINE ===

      // Round exactly like the rest of the page: (Math.round(v*10)/10).toFixed(1).
      function fmtPct(frac) { // frac on 0..1 -> "NN.N"
        if (frac == null || isNaN(frac)) return null;
        return (Math.round(frac * 100 * 10) / 10).toFixed(1);
      }

      // Read a number input as a 0..1 fraction (blank/non-numeric -> null), clamped.
      function readPct(id) {
        var inp = document.getElementById(id);
        if (!inp) return null;
        var raw = (inp.value == null ? '' : String(inp.value)).trim();
        if (raw === '') return null;
        var n = Number(raw);
        if (isNaN(n)) return null;
        if (n < 0) n = 0;
        if (n > 100) n = 100;
        return n / 100;
      }

      // -- Tabs --
      var tabToy = document.getElementById('gp-tab-toy');
      var tabReal = document.getElementById('gp-tab-real');
      var panelToy = document.getElementById('gp-panel-toy');
      var panelReal = document.getElementById('gp-panel-real');

      function selectTab(which) {
        var toy = which === 'toy';
        tabToy.setAttribute('aria-selected', toy ? 'true' : 'false');
        tabReal.setAttribute('aria-selected', toy ? 'false' : 'true');
        tabToy.tabIndex = toy ? 0 : -1;
        tabReal.tabIndex = toy ? -1 : 0;
        panelToy.hidden = !toy;
        panelReal.hidden = toy;
      }
      tabToy.addEventListener('click', function () { selectTab('toy'); });
      tabReal.addEventListener('click', function () { selectTab('real'); });
      // Arrow-key navigation across the tablist.
      function onTabKey(e) {
        if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') {
          e.preventDefault();
          var goReal = (e.currentTarget === tabToy);
          selectTab(goReal ? 'real' : 'toy');
          (goReal ? tabReal : tabToy).focus();
        }
      }
      tabToy.addEventListener('keydown', onTabKey);
      tabReal.addEventListener('keydown', onTabKey);

      // -- Tab 1: Quick toy --
      var pcSlider = document.getElementById('gp-pc');
      var workSlider = document.getElementById('gp-work');
      var pcValOut = document.getElementById('gp-pc-val');
      var workValOut = document.getElementById('gp-work-val');
      var toyGradeOut = document.getElementById('gp-toy-grade');
      var toyBranchOut = document.getElementById('gp-toy-branch');
      var barPc = document.getElementById('gp-bar-pc');
      var barWork = document.getElementById('gp-bar-work');

      function renderToy() {
        var pc = Number(pcSlider.value) / 100;   // 0..1
        var work = Number(workSlider.value) / 100;
        pcValOut.textContent = String(Math.round(pc * 100));
        workValOut.textContent = String(Math.round(work * 100));

        var grade = quarterGradeV3(pc, work);
        toyGradeOut.textContent = fmtPct(grade) + '%';

        // Bars + low-side colouring.
        barPc.style.height = Math.round(pc * 100) + '%';
        barWork.style.height = Math.round(work * 100) + '%';
        barPc.className = 'gp-bar-fill' + (pc < 0.40 ? ' low' : '');
        barWork.className = 'gp-bar-fill' + (work < 0.40 ? ' low' : '');

        // Branch explainer.
        if (pc >= 0.40 && work >= 0.40) {
          toyBranchOut.className = 'gp-branch';
          var pcWins = pc >= work;
          var trackName = pcWins ? 'Progress Checks' : 'your Work';
          toyBranchOut.innerHTML = 'We take your stronger track ('
            + '<span class="gp-win">' + trackName + '</span>): ' + fmtPct(grade) + '%';
        } else {
          toyBranchOut.className = 'gp-branch warn';
          var lowTrack = (pc < 0.40 && work < 0.40)
            ? 'both tracks'
            : (pc < 0.40 ? 'Progress Checks' : 'your Work');
          toyBranchOut.innerHTML = '&#9888; below 40% on '
            + '<span class="gp-win">' + lowTrack + '</span> &rarr; capped at 70% '
            + 'until you put a little more in.';
        }
      }

      pcSlider.addEventListener('input', renderToy);
      workSlider.addEventListener('input', renderToy);

      var presets = document.querySelectorAll('#gp-panel-toy .gp-preset');
      for (var i = 0; i < presets.length; i++) {
        presets[i].addEventListener('click', function () {
          pcSlider.value = this.getAttribute('data-pc');
          workSlider.value = this.getAttribute('data-work');
          renderToy();
        });
      }

      // -- Tab 2: Plug in real Q1 grades --
      var realPcOut = document.getElementById('gp-real-pc');
      var realWorkOut = document.getElementById('gp-real-work');
      var realGradeOut = document.getElementById('gp-real-grade');
      var realInputIds = [
        'gp-pc-u1', 'gp-pc-u2', 'gp-pc-u3',
        'gp-w-lessons', 'gp-w-quizzes', 'gp-w-posters', 'gp-w-blooket'
      ];

      function meanOf(vals) { // vals already filtered to non-null
        if (vals.length === 0) return null;
        var s = 0;
        for (var j = 0; j < vals.length; j++) s += vals[j];
        return s / vals.length;
      }

      function show(out, frac) {
        var f = fmtPct(frac);
        out.innerHTML = (f == null) ? '&mdash;' : (f + '%');
      }

      function renderReal() {
        // PC avg = mean of the ENTERED PCs.
        var pcs = [];
        var pcRaw = [readPct('gp-pc-u1'), readPct('gp-pc-u2'), readPct('gp-pc-u3')];
        for (var a = 0; a < pcRaw.length; a++) if (pcRaw[a] != null) pcs.push(pcRaw[a]);
        var pcAvg = meanOf(pcs);

        // Work avg = workAvgV3 over the ENTERED components (renormalized).
        var tracks = {
          lessons: readPct('gp-w-lessons'),
          quizzes: readPct('gp-w-quizzes'),
          posters: readPct('gp-w-posters'),
          blooket: readPct('gp-w-blooket')
        };
        var workAvg = workAvgV3(tracks);

        // Quarter grade = combineV3 (tolerates a null track).
        var grade = combineV3(pcAvg, workAvg);

        show(realPcOut, pcAvg);
        show(realWorkOut, workAvg);
        show(realGradeOut, grade);
      }

      for (var b = 0; b < realInputIds.length; b++) {
        var node = document.getElementById(realInputIds[b]);
        if (node) node.addEventListener('input', renderReal);
      }

      // Initial paint.
      renderToy();
      renderReal();
    })();
    






























































(function () {
  'use strict';

  function el(tag, attrs, children) {
    var node = document.createElement(tag);
    if (attrs) {
      for (var k in attrs) {
        if (k === 'class') node.className = attrs[k];
        else if (k === 'text') node.textContent = attrs[k];
        else if (k === 'html') node.innerHTML = attrs[k];
        else node.setAttribute(k, attrs[k]);
      }
    }
    if (children) {
      for (var i = 0; i < children.length; i++) {
        var c = children[i];
        if (c == null) continue;
        if (typeof c === 'string') node.appendChild(document.createTextNode(c));
        else node.appendChild(c);
      }
    }
    return node;
  }

  function renderSignedOut(host) {
    host.innerHTML = '';
    var wrap = el('div', { class: 'wys-signed-out' });
    wrap.appendChild(el('p', { text: 'Sign in on the Desk to see your live progress here.' }));
    wrap.appendChild(el('a', { class: 'btn', href: 'ap_stats_roadmap_square_mode.html', text: 'Open the Desk' }));
    host.appendChild(wrap);
  }

  function fmtGrade(v) {
    if (v == null || isNaN(v)) return null;
    return (Math.round(v * 10) / 10).toFixed(1);
  }

  function unitNumberFromKey(uKey) {
    var m = /^U(\d+)$/.exec(uKey);
    return m ? parseInt(m[1], 10) : null;
  }

  // Quarter band labels (must match grade-config.js quarters + the Desk roadmap).
  // SY2627: quarters are the real LEHS marking-period DATE windows; units are
  // taught in CED order and straddle quarters, so label by dates, not units.
  var QUARTER_BAND_LABEL = {
    Q1: 'Sep 2 – Nov 6',
    Q2: 'Nov 9 – Jan 22',
    Q3: 'Jan 25 – Apr 14',
    Q4: 'Apr 15 – Jun 17',
  };

  function renderQuarters(host, quarters) {
    var strip = el('div', { class: 'wys-quarters' });
    var order = ['Q1', 'Q2', 'Q3', 'Q4'];
    for (var i = 0; i < order.length; i++) {
      var qKey = order[i];
      var q = quarters && quarters[qKey];
      var grade = q ? fmtGrade(q.quarterGrade) : null;
      var ceiling = q ? fmtGrade(q.ceiling) : null;
      var graded = q && typeof q.unitsGraded === 'number' ? q.unitsGraded : null;
      var total = q && typeof q.unitsTotal === 'number' ? q.unitsTotal : null;

      var classes = 'step' + (grade == null ? ' empty' : '');
      var pill = el('span', { class: classes });
      // Tooltip: name the band + (if any work) the progress fraction.
      var bandLabel = QUARTER_BAND_LABEL[qKey] || '';
      var tip = qKey + ' covers ' + bandLabel;
      if (graded != null && total != null) {
        tip += ' — ' + graded + ' of ' + total + ' unit' + (total === 1 ? '' : 's') + ' graded';
      }
      pill.setAttribute('title', tip);
      pill.appendChild(document.createTextNode(qKey));
      pill.appendChild(el('br'));
      pill.appendChild(el('small', { html: grade == null ? '&mdash;' : grade }));
      // Motivational ceiling: present only when there's a current grade AND
      // at least one unit still to bank (ceiling > current). The server
      // returns ceiling=null in both edge cases (0 graded / all graded).
      if (ceiling != null && grade != null) {
        pill.appendChild(el('br'));
        var ceilEl = el('small', { html: '&uarr; ' + ceiling });
        ceilEl.setAttribute('title', 'If you ace the remaining ' + (total - graded) + ' unit' + ((total - graded) === 1 ? '' : 's') + ' in ' + qKey);
        ceilEl.style.color = '#25663F';
        ceilEl.style.fontSize = '0.85em';
        pill.appendChild(ceilEl);
      }
      strip.appendChild(pill);
    }
    host.appendChild(strip);
  }

  function renderUnitCard(uKey, u, completion) {
    var card = el('div', { class: 'wys-unit' });
    var unitNum = unitNumberFromKey(uKey);
    card.appendChild(el('h3', { text: unitNum ? 'Unit ' + unitNum : uKey }));

    var ug = fmtGrade(u && u.unitGrade);
    var graded = !!(u && u.graded) && ug != null;
    if (graded) {
      card.appendChild(el('div', { class: 'grade', text: ug }));
    } else {
      card.appendChild(el('div', { class: 'grade notyet', text: 'Not started yet' }));
    }

    var banked = fmtGrade(u && u.banked);
    var P = u && typeof u.P === 'number' ? u.P : 0;
    var pcText = P > 0 ? fmtGrade(P) : 'not yet';
    var parts = [];
    parts.push('Banked: ' + (banked == null ? '&mdash;' : banked));
    parts.push('Progress Check: ' + pcText);
    card.appendChild(el('p', { class: 'breakdown', html: parts.join(' &middot; ') }));

    var c = completion && completion[uKey];
    if (c) {
      var sources = [];
      var wsCount = (c.worksheet || 0) + (c.frq || 0);
      if (wsCount > 0) sources.push(wsCount + ' worksheet item' + (wsCount === 1 ? '' : 's'));
      if (c.curriculum_quiz > 0) sources.push(c.curriculum_quiz + ' quiz item' + (c.curriculum_quiz === 1 ? '' : 's'));
      if (sources.length > 0) {
        card.appendChild(el('p', { class: 'completion', html: 'Recorded: ' + sources.join(' &middot; ') }));
      }
    }
    return card;
  }

  function renderSignedIn(host, body) {
    host.innerHTML = '';
    renderQuarters(host, body.quarters || {});

    var units = body.units || {};
    var keys = Object.keys(units).sort(function (a, b) {
      var na = unitNumberFromKey(a);
      var nb = unitNumberFromKey(b);
      if (na != null && nb != null) return na - nb;
      return a.localeCompare(b);
    });

    var grid = el('div', { class: 'wys-units' });
    for (var i = 0; i < keys.length; i++) {
      grid.appendChild(renderUnitCard(keys[i], units[keys[i]], body.completion || {}));
    }
    host.appendChild(grid);

    host.appendChild(el('p', {
      class: 'note',
      html: '<em>This page reflects what we have recorded so far &mdash; your grade is the better of your work and your Progress Checks, so keep both moving.</em>'
    }));
  }

  async function init() {
    var host = document.getElementById('wys-status');
    if (!host) return;

    if (!window.rosterClient || typeof window.rosterClient.token !== 'function') {
      renderSignedOut(host);
      return;
    }

    var token = null;
    try {
      token = window.rosterClient.token();
    } catch (_) {
      token = null;
    }
    if (!token) {
      renderSignedOut(host);
      return;
    }

    var baseUrl = window.ROSTER_SERVICE_URL || null;
    if (!baseUrl) {
      renderSignedOut(host);
      return;
    }

    try {
      var response = await fetch(baseUrl + '/grade?token=' + encodeURIComponent(token));
      if (!response || !response.ok) {
        renderSignedOut(host);
        return;
      }
      var body = await response.json();
      if (!body || !body.ok) {
        renderSignedOut(host);
        return;
      }
      renderSignedIn(host, body);
    } catch (_) {
      renderSignedOut(host);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();



