#!/usr/bin/env node
// gitnexus-shadow.mjs — make the single-file HTML apps visible to GitNexus.
//
// GitNexus registers .html files but never parses their inline <script> blocks, so
// nothing inside the Desk (ap_stats_roadmap_square_mode.html, ~23k lines) resolves as
// a symbol: `gitnexus context _blooketCommit` → "not found". This script writes a
// LINE-PRESERVING JavaScript shadow of each app into .gitnexus-shadow/ (gitignored):
// every line outside an inline <script>…</script> becomes an empty line, so any
// symbol GitNexus reports at shadow line N is at line N of the real HTML file.
// External <script src> tags are skipped (those files are indexed on their own).
//
// Usage:  node scripts/gitnexus-shadow.mjs        (then `npm run gitnexus:analyze`)
// The npm script runs both. Re-run after editing an app; the shadow is derived data.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync, existsSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = resolve(ROOT, '.gitnexus-shadow');

// Single-file apps whose inline JS should be indexable. Add here when a new
// HTML app appears; worksheets (u*_lesson*_live.html) are generated and excluded.
export const SHADOWED_APPS = [
  'ap_stats_roadmap_square_mode.html',
  'mobile-home.html',
  'teacher-dashboard.html',
  'teacher-classroom.html',
  'teacher-roster-console.html',
  'study_guide_diagnostic.html',
  'start-here.html',
  'tools/level-editor.html',
];

// Returns the shadow text: same number of lines as `html`; only inline-script
// lines keep their content. Pure — unit-tested.
export function shadowOf(html) {
  const lines = String(html).split('\n');
  const out = new Array(lines.length).fill('');
  let inScript = false;
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (!inScript) {
      // Opening tag on this line? Inline only (no src=). Content after the tag stays.
      const open = /<script(\s[^>]*)?>/i.exec(line);
      if (open && !/\ssrc\s*=/i.test(open[1] || '')) {
        const after = line.slice(open.index + open[0].length);
        const close = after.search(/<\/script\s*>/i);
        if (close >= 0) {
          out[i] = after.slice(0, close);            // one-line inline script
        } else {
          out[i] = after;
          inScript = true;
        }
      }
      continue;
    }
    const close = line.search(/<\/script\s*>/i);
    // Classic-script HTML-like comments (`<!--` / `-->`) are legal in browsers
    // but not for strict JS parsers — neutralize them so the shadow parses.
    const jsLine = (l) => l.replace(/^(\s*)<!--/, '$1//<!--').replace(/^(\s*)-->/, '$1//-->');
    if (close >= 0) {
      out[i] = jsLine(line.slice(0, close));
      inScript = false;
    } else {
      out[i] = jsLine(line);
    }
  }
  return out.join('\n');
}

export function shadowFileName(htmlPath) {
  return basename(htmlPath).replace(/\.html$/i, '') + '.inline.js';
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  // Remove stale shadows for apps no longer listed.
  const keep = new Set(SHADOWED_APPS.map(shadowFileName));
  for (const f of readdirSync(OUT_DIR)) {
    if (f.endsWith('.inline.js') && !keep.has(f)) unlinkSync(resolve(OUT_DIR, f));
  }
  let written = 0;
  for (const rel of SHADOWED_APPS) {
    const src = resolve(ROOT, rel);
    if (!existsSync(src)) { console.warn(`[gitnexus-shadow] missing ${rel} — skipped`); continue; }
    const html = readFileSync(src, 'utf8');
    const shadow = shadowOf(html);
    const header = `// GENERATED by scripts/gitnexus-shadow.mjs from ${rel} — line numbers match the HTML. Do not edit.\n`;
    // Header would shift lines by one, so it replaces line 1 (always a doctype/html tag, never script).
    const lines = shadow.split('\n');
    lines[0] = header.trimEnd();
    writeFileSync(resolve(OUT_DIR, shadowFileName(rel)), lines.join('\n'), 'utf8');
    written += 1;
  }
  console.log(`[gitnexus-shadow] wrote ${written} shadow file(s) to .gitnexus-shadow/`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
