// Generated by scripts/sync-park-music.mjs from handoff/audio/tracker/tracker-engine.js — edit the handoff, then re-run the sync.
const module = { exports: {} };
/* tracker-engine.js — tiny WebAudio tracker for APStat Park (classic script, no modules).
 * TrackerEngine.create(ctx, dest, opts) -> engine
 *   engine.load(song) / play() / stop(fadeSec) / setStems({<channel or role>: level}) / mute(ch,bool) / solo(ch|null)
 *   Channels are per song (song.channels, e.g. ['drums','FM1',...,'PSG1']: one tracker channel per ORIGINAL channel).
 *   song.roles maps lead/bass/arp/pad -> a channel (used by setStems role names and by vibe.js SFX voices).
 *   song.mix[ch] = {vol (dB trim), gate (x note length), bright (x FM index), oct (shift), mute, solo}: optional per-channel
 *   hand-mix block (demo.html mixer exports it). engine.setMix(ch, {..}) changes it live; engine.getMix() returns it.
 *   Legacy songs with channels drums/bass/pad/arp/lead still load unchanged.
 *   engine.setTempoScale(x) / unlock(bool) / isUnlocked() / setMode('solo'|'class') / setLowPower(bool)
 *   engine.on('row'|'beat'|'bar'|'loop', fn) / off(evt, fn) / getClock() / nextGridTime(div)
 * Gating: LOCKED by default (easter egg) and mode 'class' by default -> play() is a no-op until
 *   unlock(true) AND (setMode('solo') or opts.allowInClass).
 * Graph: per channel: [pre-created osc] -> env -> chanGain -> stemGain -> master -> dest ; vibrato LFO -> osc.detune
 *        song.instrumentSet picks the voice family: 'nes' (pulse/tri4/LFSR noise, stepped 4-bit volume),
 *        'genesis' (2-op FM from SMPS patches, YM-style drums), 'opl2' (2-op FM, OPL waveforms). sfxOut -> dest (vibe.js)
 */
(function (root) {
'use strict';
var CH = ['drums', 'bass', 'pad', 'arp', 'lead'];   // legacy default channel list
var MAX_VOICES = 8, LP_VOICES = 5;                    // melodic voice caps (normal / lowPower)
function mtof(n) { return 440 * Math.pow(2, (n - 69) / 12); }
function pulseWave(ctx, duty) {
  var n = 64, re = new Float32Array(n), im = new Float32Array(n);
  for (var k = 1; k < n; k++) { re[k] = (2 / (k * Math.PI)) * Math.sin(2 * Math.PI * k * duty); im[k] = (2 / (k * Math.PI)) * (1 - Math.cos(2 * Math.PI * k * duty)); }
  return ctx.createPeriodicWave(re, im, { disableNormalization: false });
}
function tableWave(ctx, name) {     // tri4 = 2A03 4-bit stepped triangle; OPL2 waveforms 1-3
  var N = 256, H = 64, s = new Float32Array(N), re = new Float32Array(H), im = new Float32Array(H), i, k;
  for (i = 0; i < N; i++) {
    var ph = i / N, x = Math.sin(2 * Math.PI * ph);
    if (name === 'tri4') { var st = Math.floor(ph * 32), lv = st < 16 ? 15 - st : st - 16; x = lv / 7.5 - 1; }
    else if (name === 'halfsine') x = Math.max(0, x);
    else if (name === 'abssine') x = Math.abs(x);
    else if (name === 'quartersine') x = ((ph * 4) % 2) < 1 ? Math.abs(Math.sin(2 * Math.PI * ph)) : 0;
    s[i] = x;
  }
  for (k = 1; k < H; k++) { var a = 0, b = 0; for (i = 0; i < N; i++) { a += s[i] * Math.cos(2 * Math.PI * k * i / N); b += s[i] * Math.sin(2 * Math.PI * k * i / N); } re[k] = 2 * a / N; im[k] = 2 * b / N; }
  return ctx.createPeriodicWave(re, im, { disableNormalization: false });
}
var NES_DEFAULT = {"drums": {"kick": {"wave": "tri4", "from": 180, "to": 50, "decay": 0.09, "vol": 0.8}, "snare": {"noise": "lfsrLong", "filter": "none", "tone": 0, "decay": 0.11, "vol": 0.32, "steps": true}, "hat": {"noise": "lfsrShort", "filter": "highpass", "tone": 6000, "decay": 0.03, "vol": 0.14, "steps": true}}, "bass": {"wave": "tri4", "adsr": [0.001, 0.05, 1.0, 0.02], "vol": 0.6}, "pad": {"wave": "pulse", "duty": 0.5, "adsr": [0.06, 0.3, 0.6, 0.25], "vol": 0.08, "steps": true, "lowPowerOff": true}, "arp": {"wave": "pulse", "duty": 0.25, "adsr": [0.001, 0.08, 0.6, 0.03], "vol": 0.09, "steps": true}, "lead": {"wave": "pulse", "duty": 0.125, "adsr": [0.001, 0.12, 0.6, 0.05], "vol": 0.2, "steps": true}};
function create(ctx, dest, opts) {
  opts = opts || {};
  var LOOKAHEAD = opts.lookahead || 0.1, TIMER_MS = opts.timerMs || 25;
  var master = ctx.createGain(); master.gain.value = opts.volume != null ? opts.volume : 0.27; master.connect(dest);
  var sfxOut = ctx.createGain(); sfxOut.gain.value = opts.sfxVolume != null ? opts.sfxVolume : 0.48; sfxOut.connect(dest);
  var chan = {}, stem = {}, userLvl = {}, muted = {}, soloCh = null, CHS = CH.slice();
  function ensureChan(c) {
    if (stem[c]) return;
    stem[c] = ctx.createGain(); stem[c].connect(master);
    chan[c] = ctx.createGain(); chan[c].connect(stem[c]); userLvl[c] = 1; muted[c] = false;
  }
  CH.forEach(ensureChan);
  function resolve(c) { return (song && song.roles && song.roles[c] && !(song.channels || []).includes(c)) ? song.roles[c] : c; }
  function mixOf(c) { var m = song && song.mix && song.mix[c]; return m || {}; }
  function applyMixGains() {
    if (!song) return;
    var solo = null;
    CHS.forEach(function (c) { var m = mixOf(c); chan[c].gain.value = Math.pow(10, (m.vol || 0) / 20); if (m.solo) solo = c; });
    CHS.forEach(function (c) { muted[c] = !!mixOf(c).mute; });
    soloCh = solo;
  }
  function lpOff(c) { var i = song && song.instruments[c]; return !!(i && i.lowPowerOff !== undefined ? i.lowPowerOff : (c === 'pad' && i)); }
  var song = null, pats = null, voices = null, playing = false, timer = null;
  var unlocked = !!opts.unlocked, mode = opts.mode || 'class', allowInClass = !!opts.allowInClass, lowPower = !!opts.lowPower;
  var tempoScale = 1, listeners = { row: [], beat: [], bar: [], loop: [] };
  var pos = { order: 0, row: 0, abs: 0, time: 0 }, anchor = { time: 0, row: 0 };
  var waveCache = {}, noiseBufs = {}, voiceCount = 0;

  function rowDur() { return 60 / (song.bpm * tempoScale) / song.rowsPerBeat; }
  function tickDur() { return rowDur() / (song.ticksPerRow || 6); }
  function emit(evt, data, t) {
    var fns = listeners[evt]; if (!fns.length) return;
    var ms = Math.max(0, (t - ctx.currentTime) * 1000);
    setTimeout(function () { if (playing) fns.forEach(function (f) { try { f(data); } catch (e) { console.error(e); } }); }, ms);
  }
  function applyGains(rampSec) {
    var t = ctx.currentTime, r = rampSec == null ? 0.2 : rampSec;
    Object.keys(stem).forEach(function (c) {
      var lvl = CHS.indexOf(c) >= 0 ? userLvl[c] : 0;
      if (muted[c]) lvl = 0;
      if (soloCh && soloCh !== c) lvl = 0;
      if (lowPower && lpOff(c)) lvl = 0;
      var p = stem[c].gain; p.cancelScheduledValues(t); p.setValueAtTime(p.value, t); p.linearRampToValueAtTime(lvl, t + r);
    });
  }
  function load(s) {
    if (playing) stop(0);
    song = s; pats = {}; CHS = (s.channels || CH).slice(); CHS.forEach(ensureChan); applyMixGains();
    Object.keys(s.patterns).forEach(function (name) {
      var P = s.patterns[name], byRow = {};
      CHS.forEach(function (c) {
        (P[c] || []).forEach(function (cell) {
          var r = Math.floor(cell.r + 1e-6); (byRow[r] = byRow[r] || []).push({ ch: c, cell: cell, frac: cell.r - r });
        });
      });
      pats[name] = byRow;
    });
    applyGains(0);
    return engine;
  }
  // ---------- platform voice factory ('nes' | 'genesis' | 'opl2'); one persistent voice per channel, nodes reused ----------
  function platform() { return (song && song.instrumentSet) || 'nes'; }
  function setWave(o, name, duty) {
    if (name === 'sine' || name === 'triangle' || name === 'square' || name === 'sawtooth') { o.type = name; return; }
    var key = name === 'pulse' ? 'p' + (duty || 0.5) : name;
    if (!waveCache[key]) waveCache[key] = name === 'pulse' ? pulseWave(ctx, duty || 0.5) : tableWave(ctx, name);
    o.setPeriodicWave(waveCache[key]);
  }
  function makeVoice(inst, out, lp, mixc) {
    mixc = mixc || {};
    var car = ctx.createOscillator(), env = ctx.createGain(), lfo = ctx.createOscillator(), lfoAmt = ctx.createGain();
    setWave(car, inst.wave || 'square', inst.duty);
    env.gain.value = 0; lfo.frequency.value = 5.5; lfoAmt.gain.value = 0;
    lfo.connect(lfoAmt); lfoAmt.connect(car.detune); car.connect(env); env.connect(out);
    var fm = inst.fm, mod = null, modG = null, nodes = [car, lfo];
    if (fm && (fm.index > 0 || fm.addLevel > 0)) {
      mod = ctx.createOscillator(); setWave(mod, fm.modWave || 'sine'); lfoAmt.connect(mod.detune); nodes.push(mod);
      if (fm.addLevel > 0) { var ag = ctx.createGain(); ag.gain.value = fm.addLevel; mod.connect(ag); ag.connect(env); }   // OPL additive connection
      if (fm.index > 0) { modG = ctx.createGain(); modG.gain.value = 0; mod.connect(modG); modG.connect(car.frequency); }
    }
    return {
      inst: inst, env: env, lfo: lfo, lfoAmt: lfoAmt, osc: car, lastF: 0, nodes: nodes,
      setF: function (f, t) { car.frequency.setValueAtTime(f, t); if (mod) mod.frequency.setValueAtTime(f * fm.ratio, t); },
      freqParam: car.frequency,
      trig: function (t, gate, peak, f) {
        var a = inst.adsr || [0.005, 0.05, 0.7, 0.03];
        if (inst.steps) stepEnv(env.gain, t, gate, a[1], a[2], a[3], peak); else adsrEnv(env.gain, t, gate, a[0], a[1], a[2], a[3], peak);
        if (modG) {                                   // modulation index envelope = the FM "bright attack"
          var D = fm.index * (mixc.bright != null ? mixc.bright : 1) * f * fm.ratio, p = modG.gain; p.cancelScheduledValues(t);
          if (lp) { p.setValueAtTime(D * 0.6, t); return; }            // lowPower: fixed index, no envelope
          p.setValueAtTime(0, t); p.linearRampToValueAtTime(D, t + Math.max(0.001, fm.modAttack || 0.002));
          p.setTargetAtTime(D * (fm.modSus != null ? fm.modSus : 0.5), t + (fm.modAttack || 0.002), Math.max(0.005, (fm.modDecay || 0.3) / 3));
        }
      },
      start: function (t) { nodes.forEach(function (n) { n.start(t); }); },
      stop: function (t) { nodes.forEach(function (n) { try { n.stop(t); } catch (e) {} }); }
    };
  }
  function adsrEnv(p, t, gate, a, d, s, r, peak) {
    p.cancelScheduledValues(t);
    p.linearRampToValueAtTime(0, t + 0.002);                 // short de-click from whatever was sounding
    p.linearRampToValueAtTime(peak, t + 0.002 + a);
    p.linearRampToValueAtTime(peak * s, t + 0.002 + a + d);
    var end = Math.max(t + 0.002 + a + d, t + gate);
    p.setValueAtTime(peak * s, end);
    p.linearRampToValueAtTime(0, end + r);
  }
  function stepEnv(p, t, gate, d, s, r, peak) {           // 2A03-style 4-bit volume: 16 levels, changes on 60 Hz frames
    var F = 1 / 60, q = function (x) { return Math.round(x * 15) / 15 * peak; }, k;
    p.cancelScheduledValues(t); p.setValueAtTime(0, t); p.linearRampToValueAtTime(peak, t + 0.001);
    var frames = Math.max(1, Math.round(d / F)), last = 1;
    for (k = 1; k <= frames && t + k * F < t + gate; k++) {
      var x = 1 - (1 - s) * (k / frames), v = q(x);
      if (v !== q(last)) p.setValueAtTime(v, t + k * F); last = x;
    }
    var end = Math.max(t + 0.002, t + gate), rf = Math.max(1, Math.round(r / F));
    p.setValueAtTime(q(last), end);
    for (k = 1; k <= rf; k++) p.setValueAtTime(q(last * (1 - k / rf)), end + k * F);
  }
  function makeDrums(D, out, lp) {
    var nodes = [], K = D.kick || {}, S = D.snare || {}, H = D.hat || {};
    var kick = ctx.createOscillator(), kEnv = ctx.createGain(); setWave(kick, K.wave || 'sine'); kEnv.gain.value = 0; kick.connect(kEnv); kEnv.connect(out); nodes.push(kick);
    var tom = null, tEnv = null;
    if (D.tom && !lp) { tom = ctx.createOscillator(); setWave(tom, D.tom.wave || 'sine'); tEnv = ctx.createGain(); tEnv.gain.value = 0; tom.connect(tEnv); tEnv.connect(out); nodes.push(tom); }
    function noiseChain(spec, defFilter) {
      var src = ctx.createBufferSource(); src.buffer = noiseBuffer(spec.noise || 'white'); src.loop = true; nodes.push(src);
      var e = ctx.createGain(), ft = spec.filter || defFilter; e.gain.value = 0;
      if (ft && ft !== 'none') { var f = ctx.createBiquadFilter(); f.type = ft; f.frequency.value = spec.tone || 2000; f.Q.value = 0.8; src.connect(f); f.connect(e); } else src.connect(e);
      e.connect(out); return e;
    }
    var sEnv = noiseChain(S, 'bandpass'), hEnv = noiseChain(H, 'highpass'), body = null, bEnv = null;
    if (S.body && !lp) { body = ctx.createOscillator(); body.type = 'triangle'; bEnv = ctx.createGain(); bEnv.gain.value = 0; body.connect(bEnv); bEnv.connect(out); nodes.push(body); }
    return { D: D, kick: kick, kEnv: kEnv, tom: tom, tEnv: tEnv, sEnv: sEnv, hEnv: hEnv, body: body, bEnv: bEnv, nodes: nodes,
      start: function (t) { nodes.forEach(function (n) { n.start(t); }); }, stop: function (t) { nodes.forEach(function (n) { try { n.stop(t); } catch (e) {} }); } };
  }
  function hit(p, t, vol, dec, steps) {
    p.cancelScheduledValues(t); p.setValueAtTime(0, t); p.linearRampToValueAtTime(vol, t + 0.001);
    if (steps) { for (var k = 1; k <= 8; k++) p.setValueAtTime(vol * Math.round(15 * (1 - k / 8)) / 15, t + k * dec / 8); return; }
    p.exponentialRampToValueAtTime(0.0005, t + dec); p.setValueAtTime(0, t + dec + 0.001);
  }
  function drumHit(v, n, t, vel, cell) {
    var D = v.D;
    if (n === 'T') {                                   // original DAC tom: pitched sine drop (lowPower: kick osc)
      var T = D.tom || D.kick || {}, f0 = (cell && cell.f) || T.from || 180, o = v.tom || v.kick, e = v.tEnv || v.kEnv, td = T.decay || 0.15;
      o.frequency.cancelScheduledValues(t); o.frequency.setValueAtTime(f0, t); o.frequency.exponentialRampToValueAtTime(f0 * 0.45, t + td);
      hit(e.gain, t, (T.vol || 0.6) * vel, td, false); return;
    }
    if (n === 'K') {
      var K = D.kick || {}, dec = K.decay || 0.11;
      v.kick.frequency.cancelScheduledValues(t); v.kick.frequency.setValueAtTime(K.from || 150, t); v.kick.frequency.exponentialRampToValueAtTime(K.to || 45, t + dec);
      hit(v.kEnv.gain, t, (K.vol || 0.9) * vel, dec, false);
    } else if (n === 'S') {
      var S = D.snare || {}; hit(v.sEnv.gain, t, (S.vol || 0.3) * vel, S.decay || 0.12, S.steps);
      if (v.body) { v.body.frequency.setValueAtTime(S.body.f, t); v.body.frequency.exponentialRampToValueAtTime(S.body.f * 0.7, t + S.body.decay); hit(v.bEnv.gain, t, S.body.vol * vel, S.body.decay, false); }
    } else { var H = D.hat || {}; hit(v.hEnv.gain, t, (H.vol || 0.15) * vel, H.decay || 0.035, H.steps); }
  }
  function noiseBuffer(kind) {
    if (noiseBufs[kind]) return noiseBufs[kind];
    var sr = ctx.sampleRate, b = ctx.createBuffer(1, sr, sr), d = b.getChannelData(0), i;
    if (kind === 'white') { for (i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1; }
    else {                                               // 2A03 noise: 15-bit LFSR, long (tap 1) or short/metallic (tap 6) mode
      var tap = kind === 'lfsrShort' ? 6 : 1, rate = 1789773 / (kind === 'lfsrShort' ? 64 : 202), reg = 1, acc = 0;
      for (i = 0; i < d.length; i++) {
        acc += rate / sr;
        while (acc >= 1) { var fb = (reg ^ (reg >> tap)) & 1; reg = (reg >> 1) | (fb << 14); acc -= 1; }
        d[i] = (reg & 1) ? -1 : 1;
      }
    }
    return (noiseBufs[kind] = b);
  }
  function buildVoices() {
    var v = {}, lp = lowPower, n = 0, mel = 0;
    CHS.forEach(function (c) {
      if (c === 'drums') return;
      if (lp && lpOff(c)) return;                                     // lowPower: fewer voices (doubles / inner harmony first)
      if (mel >= (lp ? LP_VOICES : MAX_VOICES)) return;               // hard voice cap
      if (!song.mix) song.mix = {};
      if (!song.mix[c]) song.mix[c] = {};
      v[c] = makeVoice(song.instruments[c] || NES_DEFAULT[c] || NES_DEFAULT.arp, chan[c], lp && platform() !== 'nes', song.mix[c]);
      n += v[c].nodes.length; mel++;
    });
    if (CHS.indexOf('drums') >= 0) { v.drums = makeDrums(song.instruments.drums || NES_DEFAULT.drums, chan.drums, lp); n += v.drums.nodes.length; }
    var t = ctx.currentTime + 0.01;
    Object.keys(v).forEach(function (c) { v[c].start(t); });
    voiceCount = n;
    return v;
  }
  function killVoices(at) {
    if (!voices) return;
    Object.keys(voices).forEach(function (c) { voices[c].stop(at); });
    voices = null;
  }
  function playNote(c, cell, t) {
    var v = voices[c]; if (!v) return;
    var m = mixOf(c), inst = v.inst, rd = rowDur(), td = tickDur(), gate = cell.l * rd * (m.gate != null ? m.gate : 1), f = mtof(cell.n + 12 * (m.oct || 0)), fx = cell.fx || {};
    var peak = (inst.vol || 0.2) * (cell.v != null ? cell.v : 1);
    var fp = v.freqParam;
    fp.cancelScheduledValues(t);
    if (fx.slide && v.lastF) { fp.setValueAtTime(v.lastF, t); fp.exponentialRampToValueAtTime(f, t + fx.slide * td); }
    else v.setF(f, t);
    if (fx.arp && fx.arp.length > 1) {                       // tracker arpeggio: cycle offsets every arpRate ticks
      var step = (fx.arpRate || 2) * td, k = 0;
      for (var tt = t; tt < t + gate - 1e-4; tt += step, k++) v.setF(f * Math.pow(2, fx.arp[k % fx.arp.length] / 12), tt);
    }
    var la = v.lfoAmt.gain; la.cancelScheduledValues(t); la.setValueAtTime(0, t);
    if (fx.vib && !lowPower) {
      v.lfo.frequency.setValueAtTime(fx.vib[1] || 5.5, t);
      la.setValueAtTime(0, t + (fx.vib[2] || 0.1)); la.linearRampToValueAtTime((fx.vib[0] || 0.2) * 100, t + (fx.vib[2] || 0.1) + 0.08);
      la.setValueAtTime((fx.vib[0] || 0.2) * 100, t + gate); la.linearRampToValueAtTime(0, t + gate + 0.02);
    }
    v.trig(t, gate, peak, f);
    v.lastF = f;
  }
  function playDrum(cell, t) { if (voices.drums) drumHit(voices.drums, cell.n, t, cell.v != null ? cell.v : 1, cell); }
  // ---------- SFX voices for vibe.js: same factory, current platform (NES set when no song is loaded) ----------
  function sfxVoice(kind) {
    var ins = (song && song.instruments) || NES_DEFAULT, ch = (song && song.roles && song.roles[kind]) || kind;
    var src = ins[ch] || ins[kind] || ins[(song && song.roles && song.roles.lead) || 'lead'] || NES_DEFAULT[kind] || NES_DEFAULT.lead;
    if (src.fm && src.fm.ratio > 4) {                   // SFX only: high modulator ratios (e.g. OPL MULT 9) make blips sound shrill
      src = JSON.parse(JSON.stringify(src)); while (src.fm.ratio > 4) src.fm.ratio /= 2; src.fm.index *= 0.6;
    }
    var v = makeVoice(src, sfxOut, lowPower && platform() !== 'nes');
    return v;
  }
  function sfxDrum(kind, t, vel, len) {
    var D = (song && song.instruments && song.instruments.drums) || NES_DEFAULT.drums;
    var d = makeDrums(D, sfxOut, true); d.start(t);
    drumHit(d, kind === 'kick' ? 'K' : 'S', t, vel); d.stop(t + Math.max(0.2, len) + 0.05);
  }
  function scheduleRow(t) {
    var name = song.order[pos.order], byRow = pats[name], rd = rowDur();
    var swingOff = (pos.row % 2 === 1) ? (song.swing || 0) * rd : 0, tr = t + swingOff;
    (byRow[pos.row] || []).forEach(function (e) {
      var tt = tr + e.frac * rd;
      if (e.ch === 'drums') playDrum(e.cell, tt); else playNote(e.ch, e.cell, tt);
    });
    var rpb = song.rowsPerBeat, rpp = song.rowsPerPattern || 16;
    var info = { order: pos.order, pattern: name, row: pos.row, abs: pos.abs, time: t };
    emit('row', info, t);
    if (pos.row % rpb === 0) emit('beat', { beat: Math.floor(pos.abs / rpb), beatInBar: (pos.row / rpb) | 0, time: t }, t);
    if (pos.row === 0) emit('bar', { bar: pos.order, pattern: name, time: t }, t);
    anchor = { time: t, row: pos.abs };
    pos.row++; pos.abs++;
    if (pos.row >= rpp) {
      pos.row = 0; pos.order++;
      if (pos.order >= song.order.length) { pos.order = 0; emit('loop', { time: t + rd }, t + rd); if (song.loop === false) { stop(0.3); return false; } }
    }
    return true;
  }
  function tick() {
    if (!playing) return;
    while (pos.time < ctx.currentTime + LOOKAHEAD) {
      if (scheduleRow(pos.time) === false) return;
      pos.time += rowDur();
    }
    timer = setTimeout(tick, TIMER_MS);
  }
  function allowed() { return unlocked && (mode === 'solo' || allowInClass); }
  function play() {
    if (!song || playing || !allowed()) return false;
    if (ctx.state === 'suspended' && ctx.resume) ctx.resume();
    voices = buildVoices();
    var t = ctx.currentTime;
    master.gain.cancelScheduledValues(t); master.gain.setValueAtTime(opts.volume != null ? opts.volume : 0.27, t);
    pos = { order: 0, row: 0, abs: 0, time: t + 0.05 }; playing = true; applyGains(0); tick(); return true;
  }
  function stop(fade) {
    if (!playing) return;
    playing = false; clearTimeout(timer);
    var t = ctx.currentTime, f = fade == null ? 0.3 : fade, v0 = master.gain.value;
    master.gain.cancelScheduledValues(t); master.gain.setValueAtTime(v0, t); master.gain.linearRampToValueAtTime(0, t + f + 0.001);
    killVoices(t + f + 0.02);
  }
  function nextGridTime(div) {
    var now = ctx.currentTime;
    if (!playing || !song) return now;
    var step = rowDur() * (16 / (div || 16)) * (4 / song.rowsPerBeat);
    var k = Math.ceil((now + 0.005 - anchor.time) / step);
    return anchor.time + k * step;
  }
  var engine = {
    load: load, play: play, stop: stop,
    setStems: function (o) { Object.keys(o || {}).forEach(function (k0) { var k = resolve(k0); if (k in userLvl) userLvl[k] = o[k] === true ? 1 : o[k] === false ? 0 : Math.max(0, Math.min(1, +o[k] || 0)); }); applyGains(0.2); },
    mute: function (c, m) { muted[resolve(c)] = !!m; applyGains(0.05); },
    solo: function (c) { soloCh = c ? resolve(c) : null; applyGains(0.05); },
    setTempoScale: function (x) { tempoScale = Math.max(0.25, Math.min(4, +x || 1)); },
    unlock: function (on) { unlocked = on !== false; if (!allowed()) stop(0.3); return unlocked; },
    isUnlocked: function () { return unlocked; },
    setMode: function (m) { mode = m === 'solo' ? 'solo' : 'class'; if (!allowed()) stop(0.3); },
    setLowPower: function (on) { lowPower = !!on; applyGains(0.2); },
    on: function (e, fn) { if (listeners[e]) listeners[e].push(fn); return engine; },
    off: function (e, fn) { if (listeners[e]) listeners[e] = listeners[e].filter(function (f) { return f !== fn; }); },
    getClock: function () { return song ? { playing: playing, bpm: song.bpm * tempoScale, rowDur: rowDur(), rowsPerBeat: song.rowsPerBeat, order: pos.order, row: pos.row, abs: pos.abs, anchor: anchor } : { playing: false }; },
    nextGridTime: nextGridTime, sfxVoice: sfxVoice, sfxDrum: sfxDrum, platform: platform,
    getVoiceCount: function () { return voiceCount; },
    isPlaying: function () { return playing; },
    get song() { return song; }, ctx: ctx, sfxOut: sfxOut, master: master, CHANNELS: CH,
    getChannels: function () { return CHS.slice(); },
    getMix: function () { return song ? song.mix || {} : {}; },
    setMix: function (c, o) {
      if (!song) return; song.mix = song.mix || {}; var m = song.mix[c] = song.mix[c] || {};
      Object.keys(o || {}).forEach(function (k) { m[k] = o[k]; });
      applyMixGains(); applyGains(0.05);
    }
  };
  return engine;
}
var api = { create: create, CHANNELS: CH, mtof: mtof };
if (typeof module !== 'undefined' && module.exports) module.exports = api; else root.TrackerEngine = api;
})(typeof window !== 'undefined' ? window : this);
export default module.exports;
